### ISSUE TITLE
Version sent to SonarCloud in pull requests is confusing

### ISSUE THREAD

**Issue by pingvinen** [rapidcore/rapidcore#133]
In a pull request (PR) the appveyor script generates a version like `<last_released>-preview-<total number of git commits>`. This is confusing as the number of commits might change as we cleanup the history.

Instead the version from a PR could be something like `<last_released>-pr-<pr id>`.

**Comment by IceAndSnow** [comment]
Actually, I am not sure the version can be spotted on a PR in SonarCloud.
I think the confusion in SonarCloud at the moment originates from August 29, 2019 (`0.21.1-preview-726`), where the version seems to be further ahead than on August 30, 2019 (`0.21.1-preview-725`). However, this might just be due to testing the setup and integration of SonarCloud. I do not think it will be confusing after this point.
However, I have made a PR that should send the desired version format to SonarCloud on pull requests, just in case I missed the place where the version could be noticed.
