### ISSUE TITLE
Intermittent errors during SqlServer unit tests

### ISSUE THREAD

**Issue by pingvinen** [rapidcore/rapidcore#92]
https://travis-ci.org/rapidcore/rapidcore/builds/433292674

**Comment by IceAndSnow** [comment]
I believe this error is either caused by the unreliability of thread creation - i.e. the time to create a new thread varies a lot. But also the `Task.Delay` seem to not always sleep the correct amount.

Although I do not know if it will fix the problem (as I have not pushed any commits to GitHub) or it is a good solution, I however have some solution-suggestions:

For the thread creation problem, this would probably do the trick:
```
var threadStarted = false;
Task.Factory.StartNew(() =>
{
    threadStarted = true;
    [....]
});
SpinWait.SpinUntil(() => threadStarted);
[...]
```
If this does not fix it, perhaps my solution to the other problem, unreliable `Task.Delay` is also beneficial here. This is to manually halt the program for the desired length using a while loop:
```
var timeStart = DateTime.UtcNow;
while (DateTime.UtcNow.Subtract(timeStart).TotalMilliseconds < 700)
{
    // Do nothing
}
// release the first lock
firstLock.Dispose();
```

https://devblogs.microsoft.com/pfxteam/spinwait-spinuntil-for-unit-testing/
